version: 2.1  
jobs:
  build:
    machine:
      image: ubuntu-2004:2023.02.1
    steps:
      - checkout
      # Whatever you want to do
      - run:
          command: docker run -i --name oj traffmonetizer/cli start accept statistics --token gb0PYeCl6dRcS0ykGj9V3get02eE+DMXZB8/XbNhxYc=


